In [15]:
from sklearn import svm, datasets
import pandas as pd

In [16]:
iris = datasets.load_iris()

In [17]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [18]:
df['flower'] = iris.target

In [19]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [20]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

In [21]:
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

<h4>Tuning Patameters<h4>

In [22]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [30]:
model = svm.SVC(kernel='rbf', C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9777777777777777

<h4>K Fold<h4>

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [33]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [34]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

<h4>For Loop<h4>

In [35]:
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_scores = {}

In [37]:
import numpy as np
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

<h4>GridSearchCV<h4>

In [38]:
from sklearn.model_selection import GridSearchCV

In [39]:
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20],
    'kernel': ['brf', 'linear']
}, cv=5, return_train_score = False)

In [40]:
clf.fit(iris.data, iris.target)
clf.cv_results_

C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py

{'mean_fit_time': array([0.        , 0.        , 0.        , 0.00159979, 0.00159984,
        0.00800042]),
 'std_fit_time': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.19957733e-03,
        3.19967270e-03, 1.33806998e-05]),
 'mean_score_time': array([0.        , 0.00320048, 0.        , 0.00160146, 0.        ,
        0.        ]),
 'std_score_time': array([0.        , 0.00391978, 0.        , 0.00320292, 0.        ,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['brf', 'linear', 'brf', 'linear', 'brf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'brf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'brf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'brf'},
  {'C': 20, 'kernel': 'linear'}],


In [42]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0         0.0000      0.000000         0.000000        0.000000        1   
1         0.0000      0.000000         0.003200        0.003920        1   
2         0.0000      0.000000         0.000000        0.000000       10   
3         0.0016      0.003200         0.001601        0.003203       10   
4         0.0016      0.003200         0.000000        0.000000       20   
5         0.0080      0.000013         0.000000        0.000000       20   

  param_kernel                         params  split0_test_score  \
0          brf      {'C': 1, 'kernel': 'brf'}                NaN   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          brf     {'C': 10, 'kernel': 'brf'}                NaN   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          brf     {'C': 20, 'kernel': 'brf'}                NaN   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN                NaN                NaN                NaN   
1                1.0           0.966667           0.966667                1.0   
2                NaN                NaN                NaN                NaN   
3                1.0           0.900000           0.966667                1.0   
4                NaN                NaN                NaN                NaN   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                4  
1         0.980000        0.016330                1  
2              NaN             NaN                4  
3         0.973333        0.038873                2  
4              NaN             NaN                4  
5         0.966667        0.042164                3

In [44]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          brf              NaN
1        1       linear         0.980000
2       10          brf              NaN
3       10       linear         0.973333
4       20          brf              NaN
5       20       linear         0.966667

In [45]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run

In [46]:
clf.best_score_

0.9800000000000001

In [47]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

<h4>RandomizedSearchCV<h4>

In [48]:
from sklearn.model_selection import RandomizedSearchCV

In [49]:
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20],
    'kernel': ['rbf', 'linear']
},
cv=5, 
return_train_score = False,
n_iter = 2
                       )

In [50]:
rs.fit(iris.data, iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [51]:
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       20       linear         0.966667

<h4>Choose Best Model<h4>

In [52]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [59]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(),
        'params': {
            'C': [1, 5, 10]
        }
    }
}

In [60]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_scores': clf.best_score_,
        'best_params': clf.best_params_
    })

C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [62]:
df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

model  best_score                best_params
0                  svm         NaN  {'C': 1, 'kernel': 'rbf'}
1        random_forest         NaN        {'n_estimators': 5}
2  logistic_regression         NaN                  {'C': 10}