In [33]:
import pandas as pd

In [34]:
df = pd.read_csv("homeprices.csv")

<h4>Dummy Variables<h4>

In [35]:
dummies = pd.get_dummies(df.town)
merged = pd.concat([df, dummies], axis='columns')
merged.head()

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000             True        False         False
1  monroe township  3000  565000             True        False         False
2  monroe township  3200  610000             True        False         False
3  monroe township  3600  680000             True        False         False
4  monroe township  4000  725000             True        False         False

In [36]:
print(merged.columns)

Index(['town', 'area', 'price', 'monroe township', 'robinsville',
       'west windsor'],
      dtype='object')


In [37]:
final = merged.drop(['town', 'west windsor'], axis='columns')
final.head()

area   price  monroe township  robinsville
0  2600  550000             True        False
1  3000  565000             True        False
2  3200  610000             True        False
3  3600  680000             True        False
4  4000  725000             True        False

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
model = LinearRegression()

In [40]:
x = final.drop('price', axis='columns')
x.head()

area  monroe township  robinsville
0  2600             True        False
1  3000             True        False
2  3200             True        False
3  3600             True        False
4  4000             True        False

In [41]:
y = final.price
y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [42]:
model.fit(x,y)
model.predict([[2800, 0, 1]])

C:\Users\Abrar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [43]:
model.score(x,y)

0.9573929037221872

<h4>One Hot Encoding<h4>

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
le = LabelEncoder()

In [46]:
dfle = df

In [47]:
dfle.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [48]:
dfle.town = le.fit_transform(dfle.town)
dfle.head()

town  area   price
0     0  2600  550000
1     0  3000  565000
2     0  3200  610000
3     0  3600  680000
4     0  4000  725000

In [49]:
x = dfle[['town', 'area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [50]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [51]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [52]:
column_transformer = ColumnTransformer(
    transformers = [
        ('onehot', OneHotEncoder(categories= 'auto'), [0])
    ], 
    remainder = 'passthrough'
)

In [53]:
x = column_transformer.fit_transform(x)
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [54]:
type(x)

numpy.ndarray

In [55]:
x = x[:, 1:]

In [56]:
x

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [57]:
model.fit(x,y)

LinearRegression()

In [58]:
model.predict([[1, 0, 2800]])

array([590775.63964739])